CREATE OR REPLACE PROCEDURE FILLDATABASE AS 
BEGIN
  FOR COLUMN IN (SELECT TABLE_NAME FROM USER_TABLES)
  LOOP
  EPRINT(COLUMN.TABLE_NAME);
  
  TESTDATAGENERATOR2(COLUMN.TABLE_NAME, 100);
  END LOOP;
END FILLDATABASE;