-- Create temperatures table
CREATE TABLE TEMPERATURES_EINDHOVEN
  (
    "MEASUREMENTDATE" TIMESTAMP (6) NOT NULL ENABLE,
    "TEMPERATURE"     NUMBER NOT NULL ENABLE,
    CONSTRAINT "TEMPERATURES_EINDHOVEN_PK" PRIMARY KEY ("MEASUREMENTDATE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "USERS" ENABLE
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" ; 
  
-- Create XML table
CREATE TABLE "BART"."XML_TABLE"
  (
    "XMLVAL" "XMLTYPE"
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "USERS" XMLTYPE COLUMN "XMLVAL" STORE AS SECUREFILE BINARY XML
  (
    TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  )
  ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
  

-- Schedule GET_WEATHER for every 10 minutes
BEGIN                      
  DBMS_SCHEDULER.CREATE_JOB ( 
   job_name        => 'FETCH_TEMPERATURE_JOB',
   job_type        => 'PLSQL_BLOCK',       -- see oracle documentation on types --
   job_action      => 'BEGIN GET_WEATHER; END;',
   start_date      => SYSDATE,
   repeat_interval => 'FREQ=MINUTELY;BYMINUTE=10',    -- every 10 minutes.
   end_date        => NULL, 
   enabled         => TRUE,
   comments        => '');
   COMMIT;
END;
